<?php

namespace UserBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * find admin user
     * @param $admin_username
     * @return mixed
     */
    public function findOneByIdAdmin( $admin_username )
    {
        $admin = $this->getEntityManager()
            ->createQuery( 'SELECT u FROM UserBundle:User u WHERE u.username = :username' )
            ->setParameter( 'username', "$admin_username" )
            ->getResult()[0]
        ;
            return $admin;
    }

    /**
     * Return found users for current  super admin
     * @param $admin_id
     * @param int $page
     * @param string $orderBy
     * @param null $tag
     * @param int $limit
     * @return Paginator
     */
    public function findByUsers( $admin_id, $page = 0, $orderBy = 'name', $tag = null,  $limit = 7)
    {

        $query = $this->getEntityManager()
            ->createQuery( "SELECT u FROM UserBundle:Users u LEFT JOIN u.user us WHERE us.id = :id ORDER BY u.$orderBy" )
            ->setParameter( 'id', $admin_id )
            ->setMaxResults( $limit )
            ->setFirstResult( $page * $limit )
        ;

        $paginator = new Paginator( $query, $fetchJoinCollection = false );

        return $paginator;
    }
}
