UserBundle\Entity\Users:
    type: entity
    table:  users
    repositoryClass: UserBundle\Repository\UsersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
          type: string
        surname:
          type: string
        gender:
          type: string
        born:
          type: datetime
        email:
          type: string
          unequal:  false
        country:
          type: string
        city:
          type: string
        status:
          type: string
        profession:
          type: string
        token:
          type: string
    manyToOne:
      user:
        targetEntity: User
        inversedBy: users
        joinColumn:
          name: user_id
          referencedColumnName: id
    lifecycleCallbacks: {  }

