configuration_homepage:
    path:     /{page}/{sort}/{tag}
    defaults: { _controller: ConfigurationBundle:Default:welcome, page: 0, sort: name, tag: null }

configuration_database:
    path:     /{page}/{sort}/{tag}/database
    defaults: { _controller: ConfigurationBundle:Default:dataBaseConfig, page: config, sort: parameters, tag: for }

configuration_admin:
    path:     /{page}/{sort}/{tag}/admin
    defaults: { _controller: ConfigurationBundle:Default:admin, page: config, sort: parameters, tag: for }

configuration_confirmed:
    path:     /{page}/{sort}/{tag}/confirmed
    defaults: { _controller: ConfigurationBundle:Default:confirmed, page: all, sort: parameters, tag: was  }
