#homepage for any users
user_homepage:
    path:     /admin/{page}/{sort}/{tag}
    defaults: { _controller: UserBundle:Default:shows, page: 0, sort: name, tag: null }
#registration new user
register:
    path:     register/
    defaults: { _controller: UserBundle:Registration:register }
#login user for next step
login:
    path:     /login
    defaults: { _controller: UserBundle:User:index }
#path to action for SUPER ADMIN
users:
    resource: "@UserBundle/Resources/config/routes/users.yml"
    prefix:   /admin
#show registered user
register_confirmed:
    path: /register/confirmed/
    defaults: { _controller: UserBundle:Registration:confirmed }

